# Generated by Django 4.2.13 on 2024-06-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="image",
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="avatars/default_avatar.png", upload_to="avatars/"
            ),
        ),
    ]
